name: genarch
description: A utility to generate feature architecture for Flutter projects.
version: 1.0.3
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # If you need the 'path' package or any other dependencies, uncomment/add them here.

# Development-only dependencies.
dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

# This section allows the Dart SDK to recognize 'genarch' as a command-line utility.
executables:
  genarch: genarch
